apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
spec:
  selector:
    app: enrollment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
